# Site settings
title: "Commentator"
description: "Universal Web Comments - Improve transparency on the web by enabling community-driven feedback"
tagline: "Community-driven feedback for the modern web"
keywords: "web comments, community feedback, transparency, universal comments, web integration"
baseurl: ""
url: "https://kamrankhan78694.github.io/Commentator"

# Author information
author:
  name: "Kamran Khan"
  email: ""

# Social and repository information
github:
  repository_url: "https://github.com/kamrankhan78694/Commentator"
  
# SEO and site metadata
lang: en-US
locale: en_US
timezone: UTC

# Jekyll theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Minima theme settings
minima:
  skin: auto

# SEO settings
seo:
  type: WebSite
  name: "Commentator"
  links:
    - "https://kamrankhan78694.github.io/Commentator"
    - "https://github.com/kamrankhan78694/Commentator"

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      sitemap: true
  - scope:
      path: "docs"
    values:
      layout: "default"
      sitemap: true
      section: "documentation"

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - package.json
  - package-lock.json
  - node_modules/
  - .git/
  - .gitignore
  - archive/
  - test/
  - scripts/
  - "*.test.html"
  - "*-test.html"
  - debug-*
  - "*-debug.html"
  - .env*
  - database.rules*.json
  - organize-files.sh

# Include files
include:
  - _pages
  - robots.txt

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Sitemap settings
sitemap:
  exclude:
    - /archive/
    - /test/
    - /scripts/
    - "*.json"
    - "*.xml"
  include_posts:
    - "/index.html"
    - "/docs/"

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Sass settings
sass:
  sass_dir: _sass
  style: compressed